### ISSUE TITLE
/etc/sbfspot is not mapped to a directory outside the container => Config file can't be read. Please map the directory and restart the container.

### ISSUE THREAD

**Issue by TerrorSource** [nakla/sbfspot#19]
I use Portainer and created a Portainer Stacks(same as Docker Compose).
This is my config:

```
version: "3"

services:
  sbfspot:
    container_name: sbfspot
    image: nakla/sbfspot:latest
    network_mode: bridge
    environment:
      - TZ=Europe/Amsterdam
      - CSV_STORAGE=1
      - DB_STORAGE=mariadb
      - ENABLE_SBFSPOT=1
      - ENABLE_SBFSPOT_UPLOAD=1
      - FINQ=1
      - INIT_DB=0
      - MQTT_ENABLE=1
      - SBFSPOT_ARGS=-d5 -v5 -finq -nocsv -nosql
      - SBFSPOT_INTERVAL=600
    volumes:
      - /share/CACHEDEV1_DATA/Docker/sbfspot/etc:/etc/sbfspot
      - /share/CACHEDEV1_DATA/Docker/sbfspot/data:/var/sbfspot
```

It does start and automatically stops with this error:

```
/etc/sbfspot is not mapped to a directory outside the container => Config file can't be read.
Please map the directory and restart the container.
```

Already chmod and chown the folder, did not solve the issue
chmod -R 777 sbfspot/
chown -R 5000:5000 /share/CACHEDEV1_DATA/Docker/sbfspot
