### ISSUE TITLE
Interval less than 60 seconds do not work

### ISSUE THREAD

**Issue by mhilcher** [nakla/sbfspot#23]
Configured 30 seconds as interval:

```
version: '3'

services:
    sbfspot:
        image: nakla/sbfspot:latest
        network_mode: host
        volumes:
            - /mnt/usb/docker/apps/SBFSpot/conf:/etc/sbfspot
            - /mnt/usb/docker/apps/SBFSpot/data:/var/sbfspot
        environment:
            TZ: Europe/Berlin
            ENABLE_SBFSPOT: 1
            SBFSPOT_INTERVAL: 30
            ENABLE_SBFSPOT_UPLOAD: 0
            DB_STORAGE: sqlite
            CSV_STORAGE: 1
            MQTT_ENABLE: 1
            QUIET: 0
            SBFSPOT_ARGS: -d0 -v2
            INIT_DB: 0
        restart: always
``` 
Task starts every 60 seconds:
```shell
startTime: 01/09/2024 13:00:00
Reading events: 2024-Sep-01
ExportEventsToCSV()
Tue Sep 24 17:16:59 2024: INFO: Done.
Tue Sep 24 17:16:59 CEST 2024
Sleeping 60 seconds.

```
